DROP TABLE IF EXISTS "lenta_category";
CREATE TABLE IF NOT EXISTS "lenta_category" ("id" INTEGER,"name" TEXT UNIQUE,"code"	TEXT UNIQUE,PRIMARY KEY("id" AUTOINCREMENT));
DROP TABLE IF EXISTS "lenta_product";
CREATE TABLE IF NOT EXISTS "lenta_product" ("id" INTEGER,"name"	TEXT,"sub_name"	TEXT,"price"TEXT,"price_card"TEXT,"category"TEXT,PRIMARY KEY("id" AUTOINCREMENT),FOREIGN KEY("category") REFERENCES "lenta_category"("name"));
DROP TABLE IF EXISTS "lenta_status";
CREATE TABLE IF NOT EXISTS "lenta_status" (	"lastDateUpdate" TEXT);
DROP TABLE IF EXISTS "auchan_category";
CREATE TABLE IF NOT EXISTS "auchan_category" ("id" INTEGER,	"name"	TEXT UNIQUE,	PRIMARY KEY("id" AUTOINCREMENT));
DROP TABLE IF EXISTS "auchan_product";
CREATE TABLE IF NOT EXISTS "auchan_product" ("id" INTEGER,"name"	TEXT,"price"	TEXT,"category"	TEXT,PRIMARY KEY("id"),	FOREIGN KEY("category") REFERENCES "auchan_category"("name"));
DROP TABLE IF EXISTS "auchan_status";
CREATE TABLE IF NOT EXISTS "auchan_status" ("lastDateUpdate"	TEXT);
DROP TABLE IF EXISTS "metrocc_category";
CREATE TABLE IF NOT EXISTS "metrocc_category" (	"id" INTEGER,	"name"	TEXT,	"site_id"	TEXT UNIQUE,	PRIMARY KEY("id" AUTOINCREMENT));
DROP TABLE IF EXISTS "metrocc_product";
CREATE TABLE IF NOT EXISTS "metrocc_product" (	"id" INTEGER,	"name"	TEXT,	"id_category"	TEXT,	"price"	TEXT,	"price_opt"	TEXT,	"opt_count"	TEXT,	"packing"	TEXT,	PRIMARY KEY("id" AUTOINCREMENT));
DROP TABLE IF EXISTS "metrocc_status";
CREATE TABLE IF NOT EXISTS "metrocc_status" ("lastDateUpdate"	TEXT);
INSERT INTO "lenta_status" ("lastDateUpdate") VALUES ('123');
INSERT INTO "auchan_status" ("lastDateUpdate") VALUES ('123');
INSERT INTO "metrocc_status" ("lastDateUpdate") VALUES ('123');
